### ISSUE TITLE
Three important metrics not being exported

### ISSUE THREAD

**Issue by PriyankPa** [aerospike/aerospike-prometheus-exporter#20]
I am tying to monitor the key Aerospike metrics mentioned in this link:
[Key Metrics to Monitor
](https://www.aerospike.com/docs/operations/monitor/key_metrics/index.html)

Of those, following three metrics are not seen when I lookup on Prometheus:

device_available_pct
pmem_available_pct
xdr_timelag

I have tried using the latest exporter image from docker hub and also by building the image locally.

Server Details:
Aerospike Build Version: 4.7.0.5 (Running bare metal)
OS: Ubuntu 18.04
2 node cluster

**Comment by Xaelias** [comment]
You're looking for:
- aerospike_namespace_device_available_pct
- aerospike_namespace_pmem_available_pct
- aerospike_node_stats_xdr_timelag

**Comment by khaf** [comment]
It seems that we have omitted the pmem stats. Will fix ASAP.

**Comment by Xaelias** [comment]
#oops

**Comment by PriyankPa** [comment]
> It seems that we have omitted the pmem stats. Will fix ASAP.

The other two are already supposed to be available? Or they are to be added too?

**Comment by khaf** [comment]
The other two are already available.

**Comment by khaf** [comment]
`pmem` stats are also added now with the `aerospike_namespace_` prefixes.
Thank you for reporting the issue.

**Comment by PriyankPa** [comment]
> The other two are already available.

They are not available on the metrics page even in the build done today from latest code.
Do I have to configure something on the Aerospike Server or in this exporter to be able to see those metrics in the /metrics page?

**Comment by Xaelias** [comment]
Nothing special. Did you maybe filter them out in the config for the exporter?
Do you actually use device or do you have everything in memory?
Do you have XDR enabled?

**Comment by PriyankPa** [comment]
>Nothing special. Did you maybe filter them out in the config for the exporter?

I haven't made any changes to the config. Just `git clone`, `docker build` and `docker run`

> Do you actually use device or do you have everything in memory?
Just FYI I am doing only the Prometheus metrics part. I am not very familiar with aerospike.
We do store on disk but we are not using Intel Opatane DC persistent memory if that is what you mean.

> Do you have XDR enabled?
 As per the devs, we haven't enabled XDR. I was assuming we'd get all metrics with some default value if something is not enabled. 

Anyway, that still leaves aerospike_namespace_device_available_pct I suppose this metric gives the available disk pace on a conventional storage device like SSD/HDD. So I should get this metric, right?

**Comment by spkesan** [comment]
@PriyankPa 

1. `pmem_available_pct` stat will be returned by aerospike server only when there's is a PMEM storage configured in aerospike `namespace` `storage-engine` configuration.

Since you are not using PMEM (anyway PMEM as namespace data storage was introduced in 4.8). So this won't be scraped or exported. So let's remove `pmem_available_pct` from this discussion.

2. `xdr_timelag` stats should be returned by aerospike server with value `0` if XDR is not configured. **So this metric will be exported irrespective of whether you have XDR configured or not.** You should be able to see it on prometheus. **If you cannot see it on prometheus we need to debug this.**

**Can you `exec` into the exporter container and share the configuration file `cat /etc/aerospike-prometheus-exporter/ape.toml` ?
Also check `docker logs <exporterContainer>` for any errors.**

Are you connecting to the right aerospike server node? Check `AS_HOST` and `AS_PORT` environment variables in `docker run` command.

3. `device_available_pct` stat will be returned by aerospike server only when namespace `storage-engine` is `device`. If you have `storage-engine` as `device` then you must see this stat exported to prometheus.  **If you cannot see it on prometheus we need to debug this.**

**Can you share your aerospike namespace configuration as well?**

**Comment by PriyankPa** [comment]
> Can you exec into the exporter container and share the configuration file cat /etc/aerospike-prometheus-exporter/ape.toml ?



```
[Agent]
update_interval = 5

# File paths should be double quoted.
# Certificate file for the metric servers for prometheus
cert_file = ""

# Key file for the metric servers for prometheus
key_file = ""

# labels to add to the prometheus metrics for e.g. labels={zone="asia-south1-a", platform="google compute engine"}
labels = {type='development',source='aerospike'}

bind = ":9145"

# metrics server timeout in seconds
timeout = 10

# debug level can be info|warning,warn|error,err|debug
log_level = "info"

# Basic HTTP authentication for '/metrics'.
basic_auth_username=""
basic_auth_password=""

[Aerospike]
db_host="172.12.12.12"
db_port=3000

# certificate file
cert_file=""

# key file
key_file=""

# Passphrase for encrypted key_file. Supports below formats,
# 1. Passphrase directly                 - "<passphrase>"
# 2. Passphrase via file                 - "file:<file-that-contains-passphrase>"
# 3. Passphrase via environment variable - "env:<environment-variable-that-holds-passphrase>"
key_file_passphrase=""

# node TLS name for authentication
node_tls_name=""

# root certificate file
root_ca=""

# authentication mode: internal (for server), external (LDAP, etc.)
auth_mode=""

# database user
user=""

# database password
password=""

# ticker interval for requesting stats fro mthe database node
resolution=5

# timeout for sending commands to the server node in seconds
timeout=5

# Metrics Whitelist - If specified, only these metrics will be scraped. An empty list will exclude all metrics.
# Commenting out the below whitelist configs will disable whitelisting (i.e. all metrics will be scraped).

# Namespace metrics whitelist
# namespace_metrics_whitelist=[]

# Set metrics whitelist
# set_metrics_whitelist=[]

# Node metrics whitelist
# node_metrics_whitelist=[]

# XDR metrics whitelist (only for server versions 5.0 and above)
# xdr_metrics_whitelist=[]
```

> Also check docker logs <exporterContainer> for any errors.

There are no erros, just a long list of this: 

```
time="2020-05-28T20:02:42Z" level=info msg="Trying to refresh the node..."
time="2020-05-28T20:02:42Z" level=info msg="Refreshing node was successful."
time="2020-05-28T20:02:47Z" level=info msg="Trying to refresh the node..."
time="2020-05-28T20:02:47Z" level=info msg="Refreshing node was successful."
time="2020-05-28T20:02:52Z" level=info msg="Trying to refresh the node..."
time="2020-05-28T20:02:52Z" level=info msg="Refreshing node was successful."
time="2020-05-28T20:02:57Z" level=info msg="Trying to refresh the node..."
time="2020-05-28T20:02:57Z" level=info msg="Refreshing node was successful."
time="2020-05-28T20:03:02Z" level=info msg="Trying to refresh the node..."
time="2020-05-28T20:03:02Z" level=info msg="Refreshing node was successful."
time="2020-05-28T20:03:07Z" level=info msg="Trying to refresh the node..."
time="2020-05-28T20:03:07Z" level=info msg="Refreshing node was successful."
time="2020-05-28T20:03:12Z" level=info msg="Trying to refresh the node..."
time="2020-05-28T20:03:12Z" level=info msg="Refreshing node was successful."
time="2020-05-28T20:03:17Z" level=info msg="Trying to refresh the node..."
time="2020-05-28T20:03:17Z" level=info msg="Refreshing node was successful."
```

> Are you connecting to the right aerospike server node? Check AS_HOST and AS_PORT environment variables in docker run command.

Yes, it is connecting the to the right node. There are just two nodes. We are using two instances of Aerospike Prometheus exporter. Each connecting to one of the Aerospike nodes. The instance and service labels in Prometheus metrics confirm this. 
 
> Can you share your aerospike namespace configuration as well?
I will try and get back with this.

**Comment by spkesan** [comment]
Hi @PriyankPa 

Any update on this?
I double checked again, and expect the same behaviour as I mentioned [here](https://github.com/aerospike/aerospike-prometheus-exporter/issues/20#issuecomment-634476536).

**Comment by PriyankPa** [comment]
Hi, 

Sorry for the delay. We are not using `storage-engine` either. I guess you can close this.

Thanks!

**Comment by spkesan** [comment]
No problem @PriyankPa . 
Thanks for the update. I'll close this issue. Feel free to reopen this (or raise a new one) if you face any issues.
