### ISSUE TITLE
图表是否有支持

### ISSUE THREAD

**Issue by chen8770** [aerospike/aerospike-prometheus-exporter#29]
有没有grafana展示的图表

**Comment by spkesan** [comment]
Hi @chen8770 

You can find the Grafana dashboards at - 
https://github.com/aerospike/aerospike-monitoring/tree/master/config/grafana/dashboards

Please find documentation on using Aerospike Monitoring Stack at -
https://www.aerospike.com/docs/tools/monitorstack/index.html

**Comment by spkesan** [comment]
@chen8770 
Closing this issue. Feel free to reopen if you have anymore questions.
