### ISSUE TITLE
Passing root certificate as Docker environment variable

### ISSUE THREAD

**Issue by chr0mag** [aerospike/aerospike-prometheus-exporter#42]
Hello,

I'm unable to successfully pass a root certificate in as a Docker environment variable. From the [docs](https://www.aerospike.com/docs/tools/monitorstack/configure/index.html#optional-tls-and-cluster-security): "Environment variable containing base64 encoded certificate". I assume base64 encoded here means PEM.

I've tried:

- Passing the contents of a PEM file verbatim: `AS_ROOT_CA: "b64:-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----"` . The container fails to start and the following error is seen in the logs:

```level=fatal msg="Near line 45 (last key parsed 'Aerospike.root_ca'): strings cannot contain newlines"```

- Fair enough. So I strip the newlines: `AS_ROOT_CA: "b64:-----BEGIN CERTIFICATE-----...-----END CERTIFICATE-----"` . The container fails to start, but I get a different error:

```level=fatal msg="Failed to decode base64 value: illegal base64 data at input byte 0"```

- Dashes aren't legit base64 characters so strip the BEGIN... and END... sections entirely: `AS_ROOT_CA: "b64:..."`. The container starts and appears to successfully add the certificate.

```time="2021-03-06T01:18:01Z" level=info msg="Welcome to Aerospike Prometheus Exporter v1.1.6"
time="2021-03-06T01:18:01Z" level=info msg="Loading configuration file /etc/aerospike-prometheus-exporter/ape.toml"
time="2021-03-06T01:18:01Z" level=debug msg="Adding CA certificate to the pool..."
time="2021-03-06T01:18:01Z" level=info msg="Listening for Prometheus on: :9145"
```

However, if I `curl http://localhost:9145/metrics` the following appear in the logs:
```
time="2021-03-06T01:19:08Z" level=debug msg="Refreshing node 172.23.14.40:4333"
time="2021-03-06T01:19:08Z" level=debug msg="x509: certificate signed by unknown authority"
time="2021-03-06T01:19:08Z" level=debug msg="x509: certificate signed by unknown authority"
```
Ultimately I mounted the PEM file into the Docker container and referenced it directly using `AS_ROOT_CA: "file:/path/to/pem"` and this works just fine.

It appears that to get past the environment variable parsing code, we have to modify the PEM to the point where its unusable/misunderstood by the certificate handling code.

**Comment by spkesan** [comment]
@chr0mag 
You should pass the base64 encoded string of the certificate file.

For example,

Run this command,
```
base64 <path-to-root-certificate-file>
```
This will output a string which has to be set in the ENV variable.

**Comment by chr0mag** [comment]
Thanks @spkesan - that did it.

"I assume base64 encoded here means PEM." -- Looks like this was an incorrect assumption.
