### ISSUE TITLE
Wrong prometheus metric types for latencies metrics

### ISSUE THREAD

**Issue by yarosman** [aerospike/aerospike-prometheus-exporter#55]
For latencies metrics read, writes operations and requests count are used gauge type.
But if we look in [prometheus documentation](https://prometheus.io/docs/concepts/metric_types/#histogram), we will see that for such metrics it is better to use histogram.

Now we have situation when `aerospike_latencies_read_ms_count` can return float, and that is totally wrong.
With gauges we can't build correct `percentile heatmap`.

Therefore suggestion is to use histogram for such metrics type https://pkg.go.dev/github.com/prometheus/client_golang/prometheus?utm_source=godoc#Histogram

**Comment by dwelch-spike** [comment]
Hi @yarosman ,

I'm new to supporting the exporter but hopefully we can discuss this issue and find an answer.

The exporter uses the Aerospike info command "latencies:" to gather metrics for the latencies. These values are an average over the server defined ticker time unit, see [here](https://docs.aerospike.com/reference/info#latencies) for more info. That is why they can be floats. The count metric sums up the counts from all the buckets so it can also contain a float. These values can increase or decrease with time hence the gauge type.

You should be able to perform histogram queries like histogram_quantile on the bucket values using something like
`histogram_quantile(0.9, rate(aerospike_latencies_write_us_bucket{cluster_name="null", service="10.0.2.15:3000", ns=~"test"}[15m]))`

What specifically is preventing you from creating the heatmap from this data? Is it the missing sum metric? Or that the data is float?

Let me know if this helps and if you have any other thoughts.

**Comment by yarosman** [comment]
Hi, @dwelch-spike.
The main problem is that, it uses the wrong prometheus metric type for latencies.
Now, for latencies metrics `aerospike_latencies_write_us_bucket` are used gauge type, that can increase/decrease.
And indeed when you scrape data at one point of time you see metrics 
```
aerospike_latencies_write_us_bucket{le="1"} 110.3
aerospike_latencies_write_us_bucket{le="+Inf"} 110.3
```
and second later
```
aerospike_latencies_write_us_bucket{le="1"} 95.1
aerospike_latencies_write_us_bucket{le="2"} 95.7
aerospike_latencies_write_us_bucket{le="+Inf"} 95.7
```

If you look at [prometheus documentation for buckets(histograms) ](https://prometheus.io/docs/concepts/metric_types/#histogram) 
```
A histogram with a base metric name of <basename> exposes multiple time series during a scrape:

- cumulative counters for the observation buckets, exposed as <basename>_bucket{le="<upper inclusive bound>"}
- the total sum of all observed values, exposed as <basename>_sum
- the count of events that have been observed, exposed as <basename>_count (identical to <basename>_bucket{le="+Inf"} above)
```
All these metrics are `counter` - is a cumulative metric that represents a single whose value **can only increase** or be **reset to zero** on restart.

**Therefore we can't use gauge.**

_Correct heatmap with histograms_
<img width="781" alt="image" src="https://user-images.githubusercontent.com/2370255/179403679-bf5f673f-1b8f-4ba9-8d37-2c4bf4187b10.png">

_Wrong heatmap with "aerospike bucket"_
<img width="780" alt="image" src="https://user-images.githubusercontent.com/2370255/179403759-8c4e6363-7de1-486a-abcc-a492e57ff0e9.png">

So in my example correct values will be:

```
aerospike_latencies_write_ms_bucket{le="1"} 110
aerospike_latencies_write_ms_bucket{le="2"} 110
aerospike_latencies_write_ms_bucket{le="+Inf"} 110
aerospike_latencies_write_ms_count 110
aerospike_latencies_write_ms_sum 97
```
and second later
```
aerospike_latencies_write_ms_bucket{le="1"} 205
aerospike_latencies_write_ms_bucket{le="2"} 206
aerospike_latencies_write_ms_bucket{le="+Inf"} 206
aerospike_latencies_write_ms_count 206
aerospike_latencies_write_ms_sum 195
```

**Comment by yarosman** [comment]
Hello.
@dwelch-spike do you have any questions ?

**Comment by dwelch-spike** [comment]
Hi @yarosman ,

Sorry again for the long delay. We can't utilize the Prometheus histogram type because our latency data is not monotonically increasing. It is an average provided by the Aerospike server on a set interval. That's why we use gauge.

What PromQL query are you using for your heatmap dashboard? Maybe we can come up with something that will work.

**Comment by dwelch-spike** [comment]
I have a [branch](https://github.com/aerospike/aerospike-monitoring/tree/latency-rework) on the Aerospike monitoring repo where I'm experimenting with a latency heatmap that seems to be working. Maybe checking that out can help?

**Comment by Alb0t** [comment]
> branch

dead link? or private

**Comment by dwelch-spike** [comment]
it was merged and deleted. Here is the PR https://github.com/aerospike/aerospike-monitoring/pull/37

**Comment by spkesan** [comment]
Closing this issue. Please feel free re-open if needed.
