### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by Asisranjan** [aerospike/aerospike-prometheus-exporter#59]
we have no configurations of metrics in allowlist or blocklist so that means prometheus scrapes all the metrics. After successful scrapes for sometime, we observed that the promethus notifies the error "context deadline exceeded" and unable to scrape metrics. We have settings of scrape interval is 5 seconds. default scrape timeout is 10 seconds.

Thanks
Asisranjan Nayak

**Comment by spkesan** [comment]
@Asisranjan Is this on Prometheus or the exporter? I assume the error is on Prometheus logs. Can you share the exact log lines that indicate the error. Also, what do you see in the exporter logs at that time?

**Comment by Asisranjan** [comment]
when I send request to fetch metrics using curl, I could see following log message in trace logs with number of occurrence in exporter along with "Empty reply from server" as curl response
- sindex-stats (5270)
- namespace-stats (83)
- set-stats (10)
- latency-stats (10)
- node-stats (10)
- job-stats (10)

Allocated resource:
memory - 100Mi
cpu - 50m 

curl -v http://127.0.0.1:9145/metrics
*   Trying 127.0.0.1:9145...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 9145 (#0)
> GET /metrics HTTP/1.1
> Host: 127.0.0.1:9145
> User-Agent: curl/7.68.0
> Accept: */*
>


* Empty reply from server
* Connection #0 to host 127.0.0.1 left intact
curl: (52) Empty reply from server

**Comment by spkesan** [comment]
Closing this issue. Please feel free re-open if needed.
