### ISSUE TITLE
Help in determining how the aerospike exporter finds the aerospike cluster name

### ISSUE THREAD

**Issue by miande-acxiom** [aerospike/aerospike-prometheus-exporter#60]
When I perform the following search in prometheus:

`aerospike_node_stats_uptime{job="aerospike"}`

I am getting (IPs hidden):

`aerospike_node_stats_uptime{cluster_name="null", instance="X.X.X.X", job="aerospike", service="Y.Y.Y.Y:3000", source="aerospike", type="development"}`

How is the "cluster_name" set?  Is it in Aerospike configuration or from Aerospike Exporter?

**Comment by khaf** [comment]
You can set the name in the config. If you don't, the default value returned from the server will be 'null'.

**Comment by miande-acxiom** [comment]
Is this config for Aerospike or Aerospike Exporter?  Which config file?

**Comment by khaf** [comment]
Server's config:
```
service {
	...
	cluster-name <name>
}
```

**Comment by miande-acxiom** [comment]
Thank you for your quick responses.

**Comment by Flaminggay** [comment]
https://github.com/aerospike/aerospike-prometheus-exporter/issues/60#issue-1408404386
